name: Release Glab3.0

on:
  workflow_dispatch:

jobs:
  build:
    name: Release Glab3.0 Firmware
    runs-on: ubuntu-latest

    steps:
    # 下载源码
    - name: ⏬ Get nRF52-Keyboard source
      uses: actions/checkout@v2
      with:
        submodules: recursive
    # 下载安装相关工具
    - name: ⚙️ Install Tools
      run: |
        sudo apt-get update
        sudo apt-get -y install python3-pip python3-setuptools
        sudo pip3 install --upgrade pip
        sudo pip3 install nrfutil
        wget https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.0.0/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2 -O /tmp/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
        tar xf /tmp/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2 -C /tmp
        sudo cp -r /tmp/sdcc-4.0.0/* /usr/local
        wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 -O /tmp/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
        tar xf /tmp/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 -C /tmp
        wget https://github.com/genokolar/nrf52_tools/raw/main/mergehex -O /tmp/mergehex
        sudo cp -r /tmp/mergehex /usr/local/bin/mergehex
        sudo chmod 0755 /usr/local/bin/mergehex
        echo GNU_INSTALL_ROOT := /tmp/gcc-arm-none-eabi-9-2019-q4-major/bin/>template/Makefile.posix
        echo GNU_VERSION := 9.2.1>>template/Makefile.posix
        echo GNU_PREFIX := arm-none-eabi>>template/Makefile.posix
    # 编译固件
    - name: ⚒️ Make Firmware
      run: |
        cd keyboard
        make -j4
        cd ../
    # 生成发布tag
    - name: 🎉 Generate release tag
      run: |
        echo "VERSION=11`git log --abbrev-commit --pretty=oneline -1 | cut -c 1-6 || echo 'unknown'`" >> $GITHUB_ENV
        echo "BUILDTIME=`date '+%Y%m%d'`" >> $GITHUB_ENV
    # 上传编译生成的固件
    - name: 📤 Upload Artifact Files
      uses: actions/upload-artifact@v2
      with:
        name: LotKB_Keyboard_Firmware_${{ env.BUILDTIME }}_${{ env.VERSION }}
        path: |
          ${{ github.workspace }}/keyboard/_build/*.zip
          ${{ github.workspace }}/keyboard/_build/*.hex
          ${{ github.workspace }}/keyboard/_build/*.bin
    # 下载编译生成的固件      
    - name: 📥 Download Artifact Files
      uses: actions/download-artifact@v2
      with:
        name: LotKB_Keyboard_Firmware_${{ env.BUILDTIME }}_${{ env.VERSION }}
        path: ${{ github.workspace }}/keyboard/_build/Artifact
    # 打包编译生成的固件
    - name: 📦️ ZIP Artifact Files
      run:  |
        cd ${{ github.workspace }}/keyboard/_build/Artifact
        zip -r ../LotKB_Keyboard_Firmware_${{ env.BUILDTIME }}_${{ env.VERSION }}.zip *
    # 发布固件到genokolar/nrf52-keyboard库
    - name: 🎁 Release Firmware
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.BUILDTIME }}-${{ env.VERSION }}
        name: SDK17.1 ${{ env.BUILDTIME }}-${{ env.VERSION }}
        repository: genokolar/nrf52-keyboard
        generate_release_notes: true
        files: |
          ${{ github.workspace }}/keyboard/_build/*.zip
          ${{ github.workspace }}/keyboard/_build/*.hex
      env:
          GITHUB_TOKEN: ${{ secrets.KEYBOARD }}
    # 通过FTP上传到个人HOST
    - name: 📂 FTP upload firmware
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: ${{ github.workspace }}/keyboard/_build/
        server-dir: /htdocs/down/Glab3.0/
        state-name: ../.sdk17-glab3.0-firmware-sync-state.json
        exclude: "[*/**, *-nrf52*_dfu-*.zip, *-nrf52*_kbd*.hex, *-ch554-*.bin]"
    # 下载CMSIS-DAP Flasher源码
    - name: ⏬ Get CMSIS-DAP Flasher source
      uses: actions/checkout@v2
      with:
        repository: genokolar/cmsis-dap-flasher
        path: cmsis-dap-flasher
    # 为CMSIS-DAP Flasher生成hex目录存放固件
    - name: 🗃 Generate Folder
      run: |
        cd ${{ github.workspace }}/cmsis-dap-flasher
        mkdir hex
        cd ${{ github.workspace }}
    # 下载编译生成的固件      
    - name: 📥 Download Artifact Files
      uses: actions/download-artifact@v2
      with:
        name: LotKB_Keyboard_Firmware_${{ env.BUILDTIME }}_${{ env.VERSION }}
        path: ${{ github.workspace }}/cmsis-dap-flasher/hex/
    # 更新CMSIS-DAP Flasher
    - name: 📝 Update CMSIS-DAP Flasher Files
      run: |
        cd ${{ github.workspace }}/cmsis-dap-flasher
        # 替换固件版本信息
        sed -i 's/yyyymmdd-xxxxxxxx/${{ env.BUILDTIME }}-${{ env.VERSION }}/g' 开始烧录.bat
        # 转换成Windows换行符
        sed -i ':label;N;s/\n/*#/;b label' 开始烧录.bat
        sed -i 's/*#/\r\n/g' 开始烧录.bat
        # 删除HEX下多余文件
        rm -rf ./hex/*.bin
        rm -rf ./hex/*-nrf52*_dfu-*.zip
        rm -rf ./hex/*-nrf52*_kbd*.hex
        cd ${{ github.workspace }}
    # 打包CMSIS-DAP Flasher
    - name: 📦️ ZIP Artifact Files
      run:  |
        cd ${{ github.workspace }}/cmsis-dap-flasher
        zip -r CMSIS-DAP线刷包${{ env.BUILDTIME }}-${{ env.VERSION }}-SDK17.1.zip *
    
